#docker-compose.yml
version: '3'
services:
  # define your DB service - mysql
  db:
    image: mysql:5.7
    environment:
      # required mysql config, should be in sync with django settings
       MYSQL_ROOT_PASSWORD: pass
       MYSQL_DATABASE: codexpose
       MYSQL_USER: dev
       MYSQL_PASSWORD: abc@1234

  backend:
    # point build to current dir, so that it can pick Dockerfile for web image
    build: ./backend/codexpose
    # Added sleep to make sure MySql service is ready - FIXME
    environment:
      DATABASE_HOST: db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      BACKEND_HOST: backend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend